config/routes.rb
Rails.application.routes.draw do
  resources :contatos
  resources :pacientes
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contato.rb
class Contato < ApplicationRecord
  belongs_to :paciente
end

app/models/paciente.rb
class Paciente < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contatos_controller.rb
class ContatosController < ApplicationController
  before_action :set_contato, only: [:show, :edit, :update, :destroy]

  # GET /contatos
  # GET /contatos.json
  def index
    @contatos = Contato.all
  end

  # GET /contatos/1
  # GET /contatos/1.json
  def show
  end

  # GET /contatos/new
  def new
    @contato = Contato.new
  end

  # GET /contatos/1/edit
  def edit
  end

  # POST /contatos
  # POST /contatos.json
  def create
    @contato = Contato.new(contato_params)

    respond_to do |format|
      if @contato.save
        format.html { redirect_to @contato, notice: 'Contato was successfully created.' }
        format.json { render :show, status: :created, location: @contato }
      else
        format.html { render :new }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contatos/1
  # PATCH/PUT /contatos/1.json
  def update
    respond_to do |format|
      if @contato.update(contato_params)
        format.html { redirect_to @contato, notice: 'Contato was successfully updated.' }
        format.json { render :show, status: :ok, location: @contato }
      else
        format.html { render :edit }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contatos/1
  # DELETE /contatos/1.json
  def destroy
    @contato.destroy
    respond_to do |format|
      format.html { redirect_to contatos_url, notice: 'Contato was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contato
      @contato = Contato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contato_params
      params.require(:contato).permit(:ddd, :numero, :tipo, :ativo, :paciente_id)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    before_action :authenticate_user!
end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_action :set_paciente, only: [:show, :update, :destroy]

  # GET /pacientes
  # GET /pacientes.json
  def index
    @pacientes = Paciente.all
  end

  # GET /pacientes/1
  # GET /pacientes/1.json
  def show
  end

  # GET /pacientes/new
  def new
    @paciente = Paciente.new
    respond_to do |format|
      format.js { render template: 'pacientes/modal.js.erb' }
    end
  end

  # GET /pacientes/1/edit
  def edit
    @paciente = Paciente.find(params[:id])
    respond_to do |format|
      format.js { render template: 'pacientes/modal.js.erb' }
    end
  end

  # POST /pacientes
  # POST /pacientes.json
  def create
    @paciente = Paciente.new(paciente_params)

    respond_to do |format|
      if @paciente.save
        format.html { redirect_to @paciente, notice: 'Paciente was successfully created.' }
        format.json { render :show, status: :created, location: @paciente }
      else
        format.html { render :new }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacientes/1
  # PATCH/PUT /pacientes/1.json
  def update
    respond_to do |format|
      if @paciente.update(paciente_params)
        format.html { redirect_to @paciente, notice: 'Paciente was successfully updated.' }
        format.json { render :show, status: :ok, location: @paciente }
      else
        format.html { render :edit }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacientes/1
  # DELETE /pacientes/1.json
  def destroy
    @paciente.destroy
    respond_to do |format|
      format.html { redirect_to pacientes_url, notice: 'Paciente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paciente
      @paciente = Paciente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paciente_params
      params.require(:paciente).permit(:nome, :cpf, :data_nasc, :sexo, :email, :logradouro, :numero, :bairro, :cep, :cep, :cidade, :estado, :pais)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/views/contatos/_form.html.erb
<%= form_with(model: contato, local: true) do |form| %>
  <% if contato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contato.errors.count, "error") %> prohibited this contato from being saved:</h2>

      <ul>
      <% contato.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ddd %>
    <%= form.text_field :ddd, id: :contato_ddd %>
  </div>

  <div class="field">
    <%= form.label :numero %>
    <%= form.text_field :numero, id: :contato_numero %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo, id: :contato_tipo %>
  </div>

  <div class="field">
    <%= form.label :ativo %>
    <%= form.text_field :ativo, id: :contato_ativo %>
  </div>

  <div class="field">
    <%= form.label :paciente_id %>
    <%= form.text_field :paciente_id, id: :contato_paciente_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contatos/edit.html.erb
<h1>Editing Contato</h1>

<%= render 'form', contato: @contato %>

<%= link_to 'Show', @contato %> |
<%= link_to 'Back', contatos_path %>

app/views/contatos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contatos</h1>

<table>
  <thead>
    <tr>
      <th>Ddd</th>
      <th>Numero</th>
      <th>Tipo</th>
      <th>Ativo</th>
      <th>Paciente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contatos.each do |contato| %>
      <tr>
        <td><%= contato.ddd %></td>
        <td><%= contato.numero %></td>
        <td><%= contato.tipo %></td>
        <td><%= contato.ativo %></td>
        <td><%= contato.paciente %></td>
        <td><%= link_to 'Show', contato %></td>
        <td><%= link_to 'Edit', edit_contato_path(contato) %></td>
        <td><%= link_to 'Destroy', contato, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contato', new_contato_path %>

app/views/contatos/new.html.erb
<h1>New Contato</h1>

<%= render 'form', contato: @contato %>

<%= link_to 'Back', contatos_path %>

app/views/contatos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ddd:</strong>
  <%= @contato.ddd %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @contato.numero %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @contato.tipo %>
</p>

<p>
  <strong>Ativo:</strong>
  <%= @contato.ativo %>
</p>

<p>
  <strong>Paciente:</strong>
  <%= @contato.paciente %>
</p>

<%= link_to 'Edit', edit_contato_path(@contato) %> |
<%= link_to 'Back', contatos_path %>

app/views/dashboard/index.html.erb
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div id="wrapper" class="active">
      
      <!-- Sidebar -->
            <!-- Sidebar -->
      <div id="sidebar-wrapper">
        <ul id="sidebar_menu" class="sidebar-nav">
             <li class="sidebar-brand"><a class="text-custom" id="menu-toggle" href="#">Menu<span id="main_icon" class="glyphicon glyphicon-align-justify"></span></a></li>
        </ul>
        <ul class="sidebar-nav" id="sidebar">     
            <li><a href="#" class="border-li">Painel de Controle<span class="sub_icon glyphicon glyphicon-home"></span></a></li>
            <li><a href="#" class="border-li">Meus Pacientes<span class="sub_icon glyphicon glyphicon-user"></span></a></li>
             <li><a href="#" class="border-li"></a></li>
        </ul>
      </div>
          
      <!-- Page content -->
      <div id="page-content-wrapper">
        <div class="page-content inset">
          <div class="row">
              <div class="col-md-12">
                    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
                      <h5 class="my-0 mr-md-auto font-weight-normal">Company name</h5>
                      <nav class="my-2 my-md-0 mr-md-3">
                        <a class="p-2 text-dark" href="#">Features</a>
                        <a class="p-2 text-dark" href="#">Enterprise</a>
                        <a class="p-2 text-dark" href="#">Support</a>
                        <a class="p-2 text-dark" href="#">Pricing</a>
                      </nav>
                      <a class="btn btn-outline-primary" href="#">Sign up</a>
                    </div>
                    
                    <!-- Modal -->
                    <div id="myModal"></div>   
                      
                      <div class="col-md-12" style="padding:15px;">
                          <button type="button" class="btn btn-info btn-lg right ative" data-toggle="modal" data-target="#myModal">Cadastrar Paciente</button>
                          <button type="button" class="btn btn-info btn-lg right">Iniciar Consulta</button>
                          <%= link_to "New Paciente Modal", new_paciente_path, remote: true, class: "btn btn-info btn-lg right ative" %>
                      </div>
                      <div class="col-md-6">
        	<div class="carousel slide" id="carousel-964804">
        		<ol class="carousel-indicators">
        			<li data-slide-to="0" data-target="#carousel-964804">
        			</li>
        			<li data-slide-to="1" data-target="#carousel-964804" class="active">
        			</li>
        			<li data-slide-to="2" data-target="#carousel-964804">
        			</li>
        		</ol>
        		<div class="carousel-inner">
        			<div class="carousel-item active carousel-item-left">
        				<h1> teste 1</h1>
        				<div class="carousel-caption">
        					<h4>
        						First Thumbnail label
        					</h4>
        					<p>
        						Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
        					</p>
        				</div>
        			</div>
        			<div class="carousel-item carousel-item-next carousel-item-left">
        			    	<h1> teste 2</h1>
        				<div class="carousel-caption">
        					<h4>
        						Second Thumbnail label
        					</h4>
        					<p>
        						Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
        					</p>
        				</div>
        			</div>
        			<div class="carousel-item">
        			    <h1> teste 3</h1>
        				<div class="carousel-caption">
        					<h4>
        						Third Thumbnail label
        					</h4>
        					<p>
        						Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
        					</p>
        				</div>
        			</div>
        		</div> <a class="carousel-control-prev" href="#carousel-964804" data-slide="prev"><span class="carousel-control-prev-icon"></span> <span class="sr-only">Previous</span></a> <a class="carousel-control-next" href="#carousel-964804" data-slide="next"><span class="carousel-control-next-icon"></span> <span class="sr-only">Next</span></a>
        	</div>
        </div>
              
            </div>
          </div>
        </div>
      </div>
      
    </div>
    <script>
        $("#menu-toggle").click(function(e) {
                e.preventDefault();
                $("#wrapper").toggleClass("active");
        });
    </script>
    
<section class="container-fluid">
<div class="col-md-11">

        
        
 </div>
</section>

<div class="container">
  <h2>Basic Modal Example</h2>
  <!-- Trigger the modal with a button -->
  <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button>

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Modal Header</h4>
        </div>
        <div class="modal-body">
          <p>Some text in the modal.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetoWeb</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    

    <%= yield %>
  </body>
</html>

app/views/pacientes/__edit.html.erb
<h1>Editing Paciente</h1>

<%= render 'form', paciente: @paciente %>

<%= link_to 'Show', @paciente %> |
<%= link_to 'Back', pacientes_path %>

app/views/pacientes/__new.html.erb
<h1>New Paciente</h1>

<%= render 'form', paciente: @paciente %>

<%= link_to 'Back', pacientes_path %>

app/views/pacientes/_form.html.erb
<%= paciente = @paciente %>
<%= form_with(model: paciente) do |form| %>
  <% if paciente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paciente.errors.count, "error") %> prohibited this paciente from being saved:</h2>

      <ul>
      <% paciente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :paciente_nome %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf, id: :paciente_cpf %>
  </div>

  <div class="field">
    <%= form.label :data_nasc %>
    <%= form.date_select :data_nasc, id: :paciente_data_nasc %>
  </div>

  <div class="field">
    <%= form.label :sexo %>
    <%= form.text_field :sexo, id: :paciente_sexo %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :paciente_email %>
  </div>

  <div class="field">
    <%= form.label :logradouro %>
    <%= form.text_field :logradouro, id: :paciente_logradouro %>
  </div>

  <div class="field">
    <%= form.label :numero %>
    <%= form.text_field :numero, id: :paciente_numero %>
  </div>

  <div class="field">
    <%= form.label :bairro %>
    <%= form.text_field :bairro, id: :paciente_bairro %>
  </div>

  <div class="field">
    <%= form.label :cep %>
    <%= form.text_field :cep, id: :paciente_cep %>
  </div>

  <div class="field">
    <%= form.label :cep %>
    <%= form.text_field :cep, id: :paciente_cep %>
  </div>

  <div class="field">
    <%= form.label :cidade %>
    <%= form.text_field :cidade, id: :paciente_cidade %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.text_field :estado, id: :paciente_estado %>
  </div>

  <div class="field">
    <%= form.label :pais %>
    <%= form.text_field :pais, id: :paciente_pais %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pacientes/_modal.html.erb
<div class="modal fade" id="form_modal" role="modal">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <!-- <h4 class="modal-title">Modal Header</h4> -->
        <h4 class="modal-title text-center"><%= action_name.capitalize %> Paciente</h4>
      </div>
      <div class="modal-body">
        <%= render 'pacientes/form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/pacientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pacientes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th>Data nasc</th>
      <th>Sexo</th>
      <th>Email</th>
      <th>Logradouro</th>
      <th>Numero</th>
      <th>Bairro</th>
      <th>Cep</th>
      <th>Cep</th>
      <th>Cidade</th>
      <th>Estado</th>
      <th>Pais</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pacientes.each do |paciente| %>
      <tr>
        <td><%= paciente.nome %></td>
        <td><%= paciente.cpf %></td>
        <td><%= paciente.data_nasc %></td>
        <td><%= paciente.sexo %></td>
        <td><%= paciente.email %></td>
        <td><%= paciente.logradouro %></td>
        <td><%= paciente.numero %></td>
        <td><%= paciente.bairro %></td>
        <td><%= paciente.cep %></td>
        <td><%= paciente.cep %></td>
        <td><%= paciente.cidade %></td>
        <td><%= paciente.estado %></td>
        <td><%= paciente.pais %></td>
        <td><%= link_to 'Show', paciente %></td>
        <td><%= link_to 'Edit', edit_paciente_path(paciente) %></td>
        <td><%= link_to 'Destroy', paciente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paciente', new_paciente_path %>

app/views/pacientes/modal.js.erb
$("#myModal").html("<%= j render "modal" %>");
$('#form_modal').modal('show'); 

app/views/pacientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @paciente.nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @paciente.cpf %>
</p>

<p>
  <strong>Data nasc:</strong>
  <%= @paciente.data_nasc %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @paciente.sexo %>
</p>

<p>
  <strong>Email:</strong>
  <%= @paciente.email %>
</p>

<p>
  <strong>Logradouro:</strong>
  <%= @paciente.logradouro %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @paciente.numero %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @paciente.bairro %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @paciente.cep %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @paciente.cep %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @paciente.cidade %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @paciente.estado %>
</p>

<p>
  <strong>Pais:</strong>
  <%= @paciente.pais %>
</p>

<%= link_to 'Edit', edit_paciente_path(@paciente) , remote: true %> |
<%= link_to 'Back', pacientes_path %>